#pragma once

#include <vulkan/vulkan_core.h>
#include <vma/vk_mem_alloc.h>

#include "AntialiasingSettings.h"
#include "Resources/Resources.h"
#include "TextureSampler.h"
#include "Enums/ResourceUsage.h"

namespace Pudu
{
    class Texture : public GPUResource<Texture>
    {
    public:
        VkImage vkImageHandle;
        VkImageView vkImageViewHandle;
        VkDeviceMemory vkMemoryHandle;
        VmaAllocation vmaAllocation;
        TextureSampler Sampler;

        bool isSwapChain = false;
        u32 width;
        u32 height;
        u32 depth = 1;
        u32 mipLevels = 1;
        VkFormat format;
        u32 layers = 1;
        bool bindless;
        bool useAutoGeneratedMipMaps = false;
        void* sourceData;
        void* pixels;
        void* samplerData;
        u32 dataSize;

        bool IsDestroyed();

        TextureFlags::Enum GetFlags() { return m_flags; }

        GPUResourceType::Type Type() { return GPUResourceType::Texture; }
        virtual TextureType::Enum GetTextureType() { return TextureType::Texture2D; }
        void SetImageLayout(VkImageLayout layout);
        TextureSampleCount GetSampleCount() const { return m_sampleCount; }
        bool IsMultisampled() const { return m_sampleCount != TextureSampleCount::One; }
        VkImageLayout GetImageLayout() const;


        Texture()
        {
            m_flags = PopulateFlags();
        }

    protected:
        virtual TextureFlags::Enum PopulateFlags() { return TextureFlags::Default; };
        TextureSampleCount m_sampleCount = TextureSampleCount::One;

    private:
        friend PuduGraphics;
        void Destroy();
        void OnCreate(PuduGraphics* gfx) override;

        bool m_disposed;
        VkImageLayout m_layout = VK_IMAGE_LAYOUT_UNDEFINED;
        TextureFlags::Enum m_flags = TextureFlags::Default;
    };


    class RenderTexture : public Texture
    {
    public:
        void SetUsage(ResourceUsage usage);


        ResourceUsage GetUsage() const;

    protected:
        TextureFlags::Enum PopulateFlags() override { return TextureFlags::RenderTarget; };
        ResourceUsage m_usage = ResourceUsage::UNDEFINED;
    };
}
